### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by machitgarha** [ghostjat/gtk#1]
First of all, this project seems super interesting. Thanks for starting to work on it. Awesome. :)

The [GTK+ project](https://github.com/GNOME/gtk) is licensed under LGPL 2.0, but you have licensed this project under MIT. To my knowledge, because you have used modified header files of the GTK project, due to its license, the current project must be under the same license.

Could please change the license to fix this issue?

**Comment by ghostjat** [comment]
Thanks a ton,
